#168950062  register user
MakeWish/interconnweb pull request #4
Opened 2019-10-28 14:48 UTC by NicholusMuwonge

### What the PR does?
- creates factories
- created models
- creates seeders and makes migrations
- provides route for user to use in registration

### How to test it?
- pull the branch
- checkout to this branch and run `PHP artisan register`

### storyId
[#168950062](https://www.pivotaltracker.com/story/show/168950062)

2019-10-29 20:38 UTC, reifred requested changes
Thanks @NicholusMuwonge for the work done. Kindly add images for the current look of the signup form. In addition resolve merge conflicts.
Also, the part of testing this functionality is not clear.

2019-11-01 10:23 UTC, HabibSentongo requested changes
This works perfectly well on my local machine.
Kindly consider changing the `Admin` option to `Agent`
![image](https://user-images.githubusercontent.com/39903548/68018649-b30b1a80-fcaa-11e9-9a3c-85d9bb42d1e4.png)

2019-11-01 12:33 UTC, HabibSentongo approved these changes

2019-11-01 12:42 UTC, neelxie approved these changes
@NicholusMuwonge excellent stuff

2019-11-01 12:46 UTC, reifred approved these changes

2019-11-01 12:46 UTC, merged